name: WPCS check

on: push

jobs:
  phpcs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.0', '8.1', '8.2']  # Définit les versions de PHP à tester
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}  # Utilise la version de PHP de la matrice
          tools: phpcs
      - name: WPCS check using local config
        uses: 10up/wpcs-action@stable
        with:
          standard: 'phpcs.xml'
          paths: 'dianxiaomi/'
          use_local_config: true
